### ISSUE TITLE
ValueError: Can't mix absolute and relative paths

### ISSUE THREAD

**Issue by pawamoy** [billyeatcookies/biscuit#135]
## Bug

Trying to open files in the editor trigger value errors:

```console
% biscuit .     
The environment does not allow connecting to the splash screen. Are the splash resources attached to the bootloader or did an error occur?
Traceback (most recent call last):
  File "PyInstaller/fake-modules/pyi_splash.py", line 98, in <module>
  File "os.py", line 680, in __getitem__
KeyError: '_PYIBoot_SPLASH'
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter/__init__.py", line 1921, in __call__
  File "biscuit/core/components/views/sidebar/explorer/directorytree.py", line 248, in openfile
  File "biscuit/core/__init__.py", line 236, in open_editor
  File "biscuit/core/layout/base/content/editors/__init__.py", line 85, in open_editor
  File "biscuit/core/components/editors/__init__.py", line 105, in __init__
  File "biscuit/core/components/editors/breadcrumbs/__init__.py", line 23, in __init__
  File "posixpath.py", line 527, in commonpath
ValueError: Can't mix absolute and relative paths
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter/__init__.py", line 1921, in __call__
  File "biscuit/core/components/views/sidebar/explorer/directorytree.py", line 248, in openfile
  File "biscuit/core/__init__.py", line 236, in open_editor
  File "biscuit/core/layout/base/content/editors/__init__.py", line 85, in open_editor
  File "biscuit/core/components/editors/__init__.py", line 105, in __init__
  File "biscuit/core/components/editors/breadcrumbs/__init__.py", line 23, in __init__
  File "posixpath.py", line 527, in commonpath
ValueError: Can't mix absolute and relative paths
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter/__init__.py", line 1921, in __call__
  File "biscuit/core/components/views/sidebar/explorer/directorytree.py", line 248, in openfile
  File "biscuit/core/__init__.py", line 236, in open_editor
  File "biscuit/core/layout/base/content/editors/__init__.py", line 85, in open_editor
  File "biscuit/core/components/editors/__init__.py", line 105, in __init__
  File "biscuit/core/components/editors/breadcrumbs/__init__.py", line 23, in __init__
  File "posixpath.py", line 527, in commonpath
ValueError: Can't mix absolute and relative paths
```

If I open the folder in Biscuit with an absolute path instead, it works fine: `biscuit $PWD` :slightly_smiling_face: 

### System Information
- OS: ArchLinux
- Python Version: I suppose Biscuit uses the system Python so 3.11.5

**Comment by billyeatcookies** [comment]
@pawamoy this issue has been resolved. can you do a test run on latest nightly? here's the link: https://github.com/billyeatcookies/biscuit/actions/runs/7379608452

new language features such as autocompletions, goto definition and hover are added, if you can definitely try them out!
you will have to install the python extension, and the features are only supported for python for now :)

![image](https://github.com/billyeatcookies/biscuit/assets/70792552/6e49ed8b-ca79-403d-8343-319f21690c1a)

**Comment by pawamoy** [comment]
This issue seems to be fixed. I'm getting new/other ones, will open proper tickets :slightly_smiling_face:

**Comment by billyeatcookies** [comment]
Thanks for confirming ❤️ will check the new issues :)
