### ISSUE TITLE
Fix MacOS builds

### ISSUE THREAD

**Issue by billyeatcookies** [billyeatcookies/Biscuit#164]
## Bug
Errors occurring when attempting to install `tkextrafont`

```
Requirement already satisfied: pip in /Users/runner/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages (23.0.1)
Collecting pip
  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/47/6a/453160888fab7c6a432a6e25f8afe6256d0d9f2cbd25971021da6491d899/pip-23.3.1-py3-none-any.whl.metadata
  Downloading pip-23.3.1-py3-none-any.whl.metadata (3.5 kB)
Downloading pip-23.3.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 23.7 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.0.1
    Uninstalling pip-23.0.1:
      Successfully uninstalled pip-23.0.1
Successfully installed pip-23.2.1
Collecting gitpython (from -r requirements.txt (line 1))
  Downloading GitPython-3.1.40-py3-none-any.whl.metadata (12 kB)
Collecting filetype (from -r requirements.txt (line 2))
  Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Collecting tkextrafont (from -r requirements.txt (line 3))
  Downloading tkextrafont-0.6.1.tar.gz (656 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 656.8/656.8 kB 12.5 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Installing dependency cmake... Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-52w4vt39/tkextrafont_c6eed893e5fc4d1ca15a7412b331e576/setup.py", line 63, in <module>
          sp.call(["pacman", "--needed", "--noconfirm", "-S", "mingw-w64-x86_64-{}".format(dep)])  # , stdout=sp.PIPE)
        File "/Users/runner/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/subprocess.py", line 345, in call
          with Popen(*popenargs, **kwargs) as p:
        File "/Users/runner/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/Users/runner/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'pacman'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

### System Information
- OS: macos-latest
- Python Version: 3.10

**Comment by Moosems** [comment]
Yes, tkextrafont has been in maintained for quite some time.

**Comment by billyeatcookies** [comment]
@Moosems according to the tkextrafont docs, for the linux support of library they have specified some prerequisites

> This example is given for Ubuntu 20.04, change the names of packages and commands as required for your distribution of choice.
> 
> ```
> sudo apt install python3-dev tcl-dev tk-dev \
>     fontconfig libfontconfig1 libfontconfig1-dev \
>     cmake cmake-data extra-cmake-modules build-essential
> python -m pip install scikit-build
> python setup.py install 
> ```
https://github.com/TkinterEP/python-tkextrafont?tab=readme-ov-file#linux

They have not mentioned about macos support though. But what all would be the prerequisites for macos to compile the library?

**Comment by Moosems** [comment]
No idea. Depends on how the library works.

**Comment by billyeatcookies** [comment]
merging issue #86 as both mention same problem

**Comment by nkapila6** [comment]
Was trying to install it on macos and faced the same problem. Made an issue here: https://github.com/TkinterEP/python-tkextrafont/issues/14

**Comment by bennyscripts** [comment]
I managed to get tkextrafont working on Macbook M1 Air running Mac OS 15. You have to change the `pyproject.toml` file to the following:

```toml
[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "tkextrafont"
version = "1.3.0"
description = "Fonts loader for Tkinter"
authors = [{ name = "The extrafont and tkextrafont authors" }]
urls = { "Homepage" = "https://github.com/TkinterEP/tkextrafont" }

[tool.cibuildwheel]
skip = ["cp36-*", "cp37-*"]

[tool.cibuildwheel.linux]
before-all = "yum install -y tcl-devel tk-devel fontconfig-devel"

[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
before-all = "apk add tcl-dev tk-dev fontconfig-dev"

[tool.cibuildwheel.macos]
# https://github.com/actions/runner-images/issues/9441#issuecomment-1976928303
before-all = "brew install tcl-tk"
```

And had to install the dependencies through homebrew and make sure theyre in my path:
```bash
brew install tcl-tk fontconfig cmake
```
```
export PATH="/opt/homebrew/opt/tcl-tk/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/tcl-tk/lib"
export CPPFLAGS="-I/opt/homebrew/opt/tcl-tk/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/tcl-tk/lib/pkgconfig"
```

You then need to cd into the source and run the following:
```bash
python3 -m pip install scikit-build
python3 -m pip install .
```

Doing all this I managed to get tkextrafont installed but when I run biscuit I get this error:
```
_tkinter.TclError: dlopen(/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/tkinterDnD/mac/libtkdnd2.9.2.dylib, 0x0006): tried: '/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/tkinterDnD/mac/libtkdnd2.9.2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/tkinterDnD/mac/libtkdnd2.9.2.dylib' (no such file), '/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/tkinterDnD/mac/libtkdnd2.9.2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
```

The error just seems to say its incompatible with arm architecture :/

**Comment by tomlin7** [comment]
@bennyscripts amazing work, I'm impressed to see you have managed to install it. 

The error you are facing is related to tkdnd, I'm using a wrapper by @rdbende . Can you try removing the files it's used? It's only used for dnd of files/folders into the editor.

**Comment by tomlin7** [comment]
@bennyscripts I'm surprised! This is really much more than what I expected. I can see native tk widgets are looking a bit clunky in Mac, obviously, since I never thought of targeting Mac os to begin with. 

Also I doubt tkextrafont is doing any good job properly here. The icon font is the main thing I wanted out of tkextrafont, which is clearly failing here. So yeah it's tough luck. Tkinter is to become a forgotten library, so you don't have to waste your time messing with this probably. Maybe biscuit is to be rewritten in tauri/electron in future, I have a plan for that, but I'm just waiting for the right time and right people.

**Comment by nkapila6** [comment]
Love to see an update on this. Can't contribute since I use a macOS system but will try your suggestion.

**Comment by tomlin7** [comment]
@nkapila6 the editor is pretty stable now. I'm planning to also support macOS in future, if you are interested in giving this a go let me know.
